version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173" # Map container port 4173 to host port 4173
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
