version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map container port 8080 to host port 8080
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
